version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    assignees:
      - blck-snwmn
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"
    allow:
      - dependency-name: "vitest"
        versions: [ "2.*.*"]
  - package-ecosystem: "github-actions"
    directory: "/"
    assignees:
      - blck-snwmn
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"
