#:schema node_modules/wrangler/config-schema.json
name = "rsswk"
main = "src/index.ts"
compatibility_date = "2024-12-24"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[kv_namespaces]]
binding = "rss"
id = "80a0b45a3b3c43979dfc1fbad675a647"
